package com.zkpt.data.dao;

import org.apache.ibatis.annotations.Mapper;

import com.zkpt.data.entity.BankDevice;

@Mapper
public interface BankDeviceMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_bank_device
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_bank_device
     *
     * @mbggenerated
     */
    int insert(BankDevice record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_bank_device
     *
     * @mbggenerated
     */
    int insertSelective(BankDevice record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_bank_device
     *
     * @mbggenerated
     */
    BankDevice selectByPrimaryKey(Integer id);
    
    /**
     * 按银行编号查询
     * @param bankNo
     * @return
     */
    BankDevice selectByBankNo(String bankNo);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_bank_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BankDevice record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_bank_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BankDevice record);
}
