package com.zkpt.data.dao;

import org.apache.ibatis.annotations.Mapper;

import com.zkpt.data.entity.BankDeviceBehavior;

@Mapper
public interface BankDeviceBehaviorMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_bank_device_behavior
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_bank_device_behavior
     *
     * @mbggenerated
     */
    int insert(BankDeviceBehavior record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_bank_device_behavior
     *
     * @mbggenerated
     */
    int insertSelective(BankDeviceBehavior record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_bank_device_behavior
     *
     * @mbggenerated
     */
    BankDeviceBehavior selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_bank_device_behavior
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BankDeviceBehavior record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_bank_device_behavior
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BankDeviceBehavior record);
}
