package com.zkpt.data.dao;

import org.apache.ibatis.annotations.Mapper;

import com.zkpt.data.entity.GasUserBehavior;

@Mapper
public interface GasUserBehaviorMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user_behavior
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user_behavior
     *
     * @mbggenerated
     */
    int insert(GasUserBehavior record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user_behavior
     *
     * @mbggenerated
     */
    int insertSelective(GasUserBehavior record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user_behavior
     *
     * @mbggenerated
     */
    GasUserBehavior selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user_behavior
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GasUserBehavior record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user_behavior
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GasUserBehavior record);
}
