package com.zkpt.data.dao;

import org.apache.ibatis.annotations.Mapper;

import com.zkpt.data.entity.GasUser;

@Mapper
public interface GasUserMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user
     *
     * @mbggenerated
     */
    int insert(GasUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user
     *
     * @mbggenerated
     */
    int insertSelective(GasUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user
     *
     * @mbggenerated
     */
    GasUser selectByPrimaryKey(Integer id);
    
    /**
     * 按用户编号查询
     * 
     * @param userNo 用户编码
     * @return
     */
    GasUser selectByUserNo(String userNo);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GasUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GasUser record);
}
