package com.zkpt.data.dao;

import org.apache.ibatis.annotations.Mapper;

import com.zkpt.data.entity.Operation;

@Mapper
public interface OperationMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_operation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_operation
     *
     * @mbggenerated
     */
    int insert(Operation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_operation
     *
     * @mbggenerated
     */
    int insertSelective(Operation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_operation
     *
     * @mbggenerated
     */
    Operation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_operation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Operation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_operation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Operation record);
}
