#通用配置
#==================== Tomcat·服务器 ============================
server:
    port: 8081
    session-timeout: 3600
    servlet:
        context-path: /zkpt
    tomcat:
        uri-encoding: utf-8
  
  
#==================== 日志配合·标准  ============================
logging:
    config: classpath:logback-boot.xml

#==================== 中间件 == ==============================
middleware:
    server:
        bank:
            ip: 192.168.1.124
            port: 60001
            bufferSize: 2048
            idleTime: 10
            loggerFilterName: logger
            referenceCountingFilterName: myIoFilter
            protocolCodecFilterName: coderc
            charSetName: gbk
        ftp:
            ip: 35.200.99.89
            port: 21
            user: cctest
            pwd: b8GLFzexJR
            workpath:
    client:
        gas:
            ip: 192.168.1.124
            port: 10002
            connectTimeoutMillis: 20000
            readBufferSize: 1024
            both_idle: 10
            reader_idle: 15
            writer_idle: 15
            loggerFilterName: logger
            referenceCountingFilterName: myIoFilter
            protocolCodecFilterName: coderc
            charSetName: gbk
        ftp:
            ip:
            port:
            user:
            pwd:
            workpath:

bank:
    code: '0008'
 
#==================== 数据库 =================================
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        name: zkpt
        url: jdbc:mysql://192.168.1.200:3306/zkpt?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 12ab!@
        driver-class-name: com.mysql.jdbc.Driver
        # 下面为连接池的补充设置，应用到上面所有数据源中
        initialSize: 1 # 初始化大小
        minIdle: 3 # 初始化最小
        maxActive: 20 # 初始化最大
        maxWait: 60000 # 配置获取连接等待超时的时间
        timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis: 30000 # 配置一个连接在池中最小生存的时间，单位是毫秒
        testWhileIdle: false #validationQuery: select 'x'
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        use-global-data-source-stat: true # 合并多个DruidDataSource的监控数据
    rabbitmq:
        addresses: 192.168.1.124
        port: 5672
        username: zkpt
        password: 12ab!@
        publisher-confirms: false
        virtual-host: /
    cache:
        redis: 
            time-to-live: 60s
        type: redis
    redis:
        database: 0  # 数据库索引（默认为0）
        host: 192.168.1.124
        port: 6379
        password: foobared # 服务器连接密码（默认为空）
        lettuce:
            pool:
                max-idle: 25 # 连接池中的最大空闲连接
                min-idle: 1 # 连接池中的最小空闲连接
                max-active: 50 # 连接池最大连接数（使用负值表示没有限制）  
                max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        timeout: 30000 # 连接超时时间（毫秒） 
    thymeleaf:
        cache: false
    output:
        ansi:
            enabled: ALWAYS
    mvc:
        favicon:
            enabled: false

#==================== mybatis存储 ===========================
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  config-locations: classpath:mybatis-config.xml
  type-aliases-package: com.zkpt
  
#==================== 银行测试客户端 ==========================
test:
    client:
        bank:
            connectTimeoutMillis: 5000
            loggerFilterName: logger
            referenceCountingFilterName: myIoFilter
            protocolCodecFilterName: coderc
            charSetName: gbk