package com.zkpt.data.entity;

import java.io.Serializable;
import java.util.Date;

public class BankDevice implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_bank_device.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_bank_device.BANK_NO
     *
     * @mbggenerated
     */
    private String bankNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_bank_device.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_bank_device.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_bank_device.UPDATE_BY
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_bank_device.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_bank_device.DELFLAG
     *
     * @mbggenerated
     */
    private Short delflag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_bank_device.DEL_DATE
     *
     * @mbggenerated
     */
    private Date delDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * mid_bank_device
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_bank_device.ID
     *
     * @return the value of mid_bank_device.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_bank_device.ID
     *
     * @param id the value for mid_bank_device.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_bank_device.BANK_NO
     *
     * @return the value of mid_bank_device.BANK_NO
     *
     * @mbggenerated
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_bank_device.BANK_NO
     *
     * @param bankNo the value for mid_bank_device.BANK_NO
     *
     * @mbggenerated
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_bank_device.CREATE_BY
     *
     * @return the value of mid_bank_device.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_bank_device.CREATE_BY
     *
     * @param createBy the value for mid_bank_device.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_bank_device.CREATE_DATE
     *
     * @return the value of mid_bank_device.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_bank_device.CREATE_DATE
     *
     * @param createDate the value for mid_bank_device.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_bank_device.UPDATE_BY
     *
     * @return the value of mid_bank_device.UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_bank_device.UPDATE_BY
     *
     * @param updateBy the value for mid_bank_device.UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_bank_device.UPDATE_DATE
     *
     * @return the value of mid_bank_device.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_bank_device.UPDATE_DATE
     *
     * @param updateDate the value for mid_bank_device.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_bank_device.DELFLAG
     *
     * @return the value of mid_bank_device.DELFLAG
     *
     * @mbggenerated
     */
    public Short getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_bank_device.DELFLAG
     *
     * @param delflag the value for mid_bank_device.DELFLAG
     *
     * @mbggenerated
     */
    public void setDelflag(Short delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_bank_device.DEL_DATE
     *
     * @return the value of mid_bank_device.DEL_DATE
     *
     * @mbggenerated
     */
    public Date getDelDate() {
        return delDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_bank_device.DEL_DATE
     *
     * @param delDate the value for mid_bank_device.DEL_DATE
     *
     * @mbggenerated
     */
    public void setDelDate(Date delDate) {
        this.delDate = delDate;
    }
}
