package com.zkpt.data.entity;

import java.io.Serializable;
import java.util.Date;

public class GasUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user.USER_NO
     *
     * @mbggenerated
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user.UPDATE_BY
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user.DELFLAG
     *
     * @mbggenerated
     */
    private Short delflag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user.DEL_DATE
     *
     * @mbggenerated
     */
    private Date delDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * mid_gas_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user.ID
     *
     * @return the value of mid_gas_user.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user.ID
     *
     * @param id the value for mid_gas_user.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user.USER_NAME
     *
     * @return the value of mid_gas_user.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user.USER_NAME
     *
     * @param userName the value for mid_gas_user.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user.USER_NO
     *
     * @return the value of mid_gas_user.USER_NO
     *
     * @mbggenerated
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user.USER_NO
     *
     * @param userNo the value for mid_gas_user.USER_NO
     *
     * @mbggenerated
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user.CREATE_BY
     *
     * @return the value of mid_gas_user.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user.CREATE_BY
     *
     * @param createBy the value for mid_gas_user.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user.CREATE_DATE
     *
     * @return the value of mid_gas_user.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user.CREATE_DATE
     *
     * @param createDate the value for mid_gas_user.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user.UPDATE_BY
     *
     * @return the value of mid_gas_user.UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user.UPDATE_BY
     *
     * @param updateBy the value for mid_gas_user.UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user.UPDATE_DATE
     *
     * @return the value of mid_gas_user.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user.UPDATE_DATE
     *
     * @param updateDate the value for mid_gas_user.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user.DELFLAG
     *
     * @return the value of mid_gas_user.DELFLAG
     *
     * @mbggenerated
     */
    public Short getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user.DELFLAG
     *
     * @param delflag the value for mid_gas_user.DELFLAG
     *
     * @mbggenerated
     */
    public void setDelflag(Short delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user.DEL_DATE
     *
     * @return the value of mid_gas_user.DEL_DATE
     *
     * @mbggenerated
     */
    public Date getDelDate() {
        return delDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user.DEL_DATE
     *
     * @param delDate the value for mid_gas_user.DEL_DATE
     *
     * @mbggenerated
     */
    public void setDelDate(Date delDate) {
        this.delDate = delDate;
    }
}
