package com.zkpt.data.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class GasUserCost implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.USER_NO
     *
     * @mbggenerated
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.MONTH
     *
     * @mbggenerated
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.PREV_VAL
     *
     * @mbggenerated
     */
    private BigDecimal prevVal;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.CURR_VAL
     *
     * @mbggenerated
     */
    private BigDecimal currVal;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.AIR_VAL
     *
     * @mbggenerated
     */
    private BigDecimal airVal;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.AIR_COST
     *
     * @mbggenerated
     */
    private BigDecimal airCost;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.PAY_ABLE_AIR_NUM
     *
     * @mbggenerated
     */
    private BigDecimal payAbleAirNum;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.LATE_FEE
     *
     * @mbggenerated
     */
    private BigDecimal lateFee;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.PAY_ABLE_AIR_COST
     *
     * @mbggenerated
     */
    private BigDecimal payAbleAirCost;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.AIR_VAL1
     *
     * @mbggenerated
     */
    private BigDecimal airVal1;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.AIR_COST1
     *
     * @mbggenerated
     */
    private BigDecimal airCost1;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.AIR_VAL2
     *
     * @mbggenerated
     */
    private BigDecimal airVal2;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.AIR_COST2
     *
     * @mbggenerated
     */
    private BigDecimal airCost2;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.AIR_VAL3
     *
     * @mbggenerated
     */
    private BigDecimal airVal3;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.AIR_COST3
     *
     * @mbggenerated
     */
    private BigDecimal airCost3;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.AIR_VAL4
     *
     * @mbggenerated
     */
    private BigDecimal airVal4;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.AIR_COST4
     *
     * @mbggenerated
     */
    private BigDecimal airCost4;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.UPDATE_BY
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.DELFLAG
     *
     * @mbggenerated
     */
    private Short delflag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_gas_user_cost.DEL_DATE
     *
     * @mbggenerated
     */
    private Date delDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * mid_gas_user_cost
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.ID
     *
     * @return the value of mid_gas_user_cost.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.ID
     *
     * @param id the value for mid_gas_user_cost.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.USER_NAME
     *
     * @return the value of mid_gas_user_cost.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.USER_NAME
     *
     * @param userName the value for mid_gas_user_cost.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.USER_NO
     *
     * @return the value of mid_gas_user_cost.USER_NO
     *
     * @mbggenerated
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.USER_NO
     *
     * @param userNo the value for mid_gas_user_cost.USER_NO
     *
     * @mbggenerated
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.MONTH
     *
     * @return the value of mid_gas_user_cost.MONTH
     *
     * @mbggenerated
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.MONTH
     *
     * @param month the value for mid_gas_user_cost.MONTH
     *
     * @mbggenerated
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.PREV_VAL
     *
     * @return the value of mid_gas_user_cost.PREV_VAL
     *
     * @mbggenerated
     */
    public BigDecimal getPrevVal() {
        return prevVal;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.PREV_VAL
     *
     * @param prevVal the value for mid_gas_user_cost.PREV_VAL
     *
     * @mbggenerated
     */
    public void setPrevVal(BigDecimal prevVal) {
        this.prevVal = prevVal;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.CURR_VAL
     *
     * @return the value of mid_gas_user_cost.CURR_VAL
     *
     * @mbggenerated
     */
    public BigDecimal getCurrVal() {
        return currVal;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.CURR_VAL
     *
     * @param currVal the value for mid_gas_user_cost.CURR_VAL
     *
     * @mbggenerated
     */
    public void setCurrVal(BigDecimal currVal) {
        this.currVal = currVal;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.AIR_VAL
     *
     * @return the value of mid_gas_user_cost.AIR_VAL
     *
     * @mbggenerated
     */
    public BigDecimal getAirVal() {
        return airVal;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.AIR_VAL
     *
     * @param airVal the value for mid_gas_user_cost.AIR_VAL
     *
     * @mbggenerated
     */
    public void setAirVal(BigDecimal airVal) {
        this.airVal = airVal;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.AIR_COST
     *
     * @return the value of mid_gas_user_cost.AIR_COST
     *
     * @mbggenerated
     */
    public BigDecimal getAirCost() {
        return airCost;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.AIR_COST
     *
     * @param airCost the value for mid_gas_user_cost.AIR_COST
     *
     * @mbggenerated
     */
    public void setAirCost(BigDecimal airCost) {
        this.airCost = airCost;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.PAY_ABLE_AIR_NUM
     *
     * @return the value of mid_gas_user_cost.PAY_ABLE_AIR_NUM
     *
     * @mbggenerated
     */
    public BigDecimal getPayAbleAirNum() {
        return payAbleAirNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.PAY_ABLE_AIR_NUM
     *
     * @param payAbleAirNum the value for mid_gas_user_cost.PAY_ABLE_AIR_NUM
     *
     * @mbggenerated
     */
    public void setPayAbleAirNum(BigDecimal payAbleAirNum) {
        this.payAbleAirNum = payAbleAirNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.LATE_FEE
     *
     * @return the value of mid_gas_user_cost.LATE_FEE
     *
     * @mbggenerated
     */
    public BigDecimal getLateFee() {
        return lateFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.LATE_FEE
     *
     * @param lateFee the value for mid_gas_user_cost.LATE_FEE
     *
     * @mbggenerated
     */
    public void setLateFee(BigDecimal lateFee) {
        this.lateFee = lateFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.PAY_ABLE_AIR_COST
     *
     * @return the value of mid_gas_user_cost.PAY_ABLE_AIR_COST
     *
     * @mbggenerated
     */
    public BigDecimal getPayAbleAirCost() {
        return payAbleAirCost;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.PAY_ABLE_AIR_COST
     *
     * @param payAbleAirCost the value for mid_gas_user_cost.PAY_ABLE_AIR_COST
     *
     * @mbggenerated
     */
    public void setPayAbleAirCost(BigDecimal payAbleAirCost) {
        this.payAbleAirCost = payAbleAirCost;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.AIR_VAL1
     *
     * @return the value of mid_gas_user_cost.AIR_VAL1
     *
     * @mbggenerated
     */
    public BigDecimal getAirVal1() {
        return airVal1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.AIR_VAL1
     *
     * @param airVal1 the value for mid_gas_user_cost.AIR_VAL1
     *
     * @mbggenerated
     */
    public void setAirVal1(BigDecimal airVal1) {
        this.airVal1 = airVal1;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.AIR_COST1
     *
     * @return the value of mid_gas_user_cost.AIR_COST1
     *
     * @mbggenerated
     */
    public BigDecimal getAirCost1() {
        return airCost1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.AIR_COST1
     *
     * @param airCost1 the value for mid_gas_user_cost.AIR_COST1
     *
     * @mbggenerated
     */
    public void setAirCost1(BigDecimal airCost1) {
        this.airCost1 = airCost1;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.AIR_VAL2
     *
     * @return the value of mid_gas_user_cost.AIR_VAL2
     *
     * @mbggenerated
     */
    public BigDecimal getAirVal2() {
        return airVal2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.AIR_VAL2
     *
     * @param airVal2 the value for mid_gas_user_cost.AIR_VAL2
     *
     * @mbggenerated
     */
    public void setAirVal2(BigDecimal airVal2) {
        this.airVal2 = airVal2;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.AIR_COST2
     *
     * @return the value of mid_gas_user_cost.AIR_COST2
     *
     * @mbggenerated
     */
    public BigDecimal getAirCost2() {
        return airCost2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.AIR_COST2
     *
     * @param airCost2 the value for mid_gas_user_cost.AIR_COST2
     *
     * @mbggenerated
     */
    public void setAirCost2(BigDecimal airCost2) {
        this.airCost2 = airCost2;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.AIR_VAL3
     *
     * @return the value of mid_gas_user_cost.AIR_VAL3
     *
     * @mbggenerated
     */
    public BigDecimal getAirVal3() {
        return airVal3;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.AIR_VAL3
     *
     * @param airVal3 the value for mid_gas_user_cost.AIR_VAL3
     *
     * @mbggenerated
     */
    public void setAirVal3(BigDecimal airVal3) {
        this.airVal3 = airVal3;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.AIR_COST3
     *
     * @return the value of mid_gas_user_cost.AIR_COST3
     *
     * @mbggenerated
     */
    public BigDecimal getAirCost3() {
        return airCost3;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.AIR_COST3
     *
     * @param airCost3 the value for mid_gas_user_cost.AIR_COST3
     *
     * @mbggenerated
     */
    public void setAirCost3(BigDecimal airCost3) {
        this.airCost3 = airCost3;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.AIR_VAL4
     *
     * @return the value of mid_gas_user_cost.AIR_VAL4
     *
     * @mbggenerated
     */
    public BigDecimal getAirVal4() {
        return airVal4;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.AIR_VAL4
     *
     * @param airVal4 the value for mid_gas_user_cost.AIR_VAL4
     *
     * @mbggenerated
     */
    public void setAirVal4(BigDecimal airVal4) {
        this.airVal4 = airVal4;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.AIR_COST4
     *
     * @return the value of mid_gas_user_cost.AIR_COST4
     *
     * @mbggenerated
     */
    public BigDecimal getAirCost4() {
        return airCost4;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.AIR_COST4
     *
     * @param airCost4 the value for mid_gas_user_cost.AIR_COST4
     *
     * @mbggenerated
     */
    public void setAirCost4(BigDecimal airCost4) {
        this.airCost4 = airCost4;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.CREATE_BY
     *
     * @return the value of mid_gas_user_cost.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.CREATE_BY
     *
     * @param createBy the value for mid_gas_user_cost.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.CREATE_DATE
     *
     * @return the value of mid_gas_user_cost.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.CREATE_DATE
     *
     * @param createDate the value for mid_gas_user_cost.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.UPDATE_BY
     *
     * @return the value of mid_gas_user_cost.UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.UPDATE_BY
     *
     * @param updateBy the value for mid_gas_user_cost.UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.UPDATE_DATE
     *
     * @return the value of mid_gas_user_cost.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.UPDATE_DATE
     *
     * @param updateDate the value for mid_gas_user_cost.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.DELFLAG
     *
     * @return the value of mid_gas_user_cost.DELFLAG
     *
     * @mbggenerated
     */
    public Short getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.DELFLAG
     *
     * @param delflag the value for mid_gas_user_cost.DELFLAG
     *
     * @mbggenerated
     */
    public void setDelflag(Short delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_gas_user_cost.DEL_DATE
     *
     * @return the value of mid_gas_user_cost.DEL_DATE
     *
     * @mbggenerated
     */
    public Date getDelDate() {
        return delDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_gas_user_cost.DEL_DATE
     *
     * @param delDate the value for mid_gas_user_cost.DEL_DATE
     *
     * @mbggenerated
     */
    public void setDelDate(Date delDate) {
        this.delDate = delDate;
    }
}
