package com.zkpt.data.entity;

import java.io.Serializable;
import java.util.Date;

public class Operation implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_operation.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_operation.BANK_IP
     *
     * @mbggenerated
     */
    private String bankIp;


    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_operation.BANK_PORT
     *
     * @mbggenerated
     */
    private Integer bankPort;


    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_operation.BANK_SEND
     *
     * @mbggenerated
     */
    private String bankSend;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_operation.BANK_SEND_TIME
     *
     * @mbggenerated
     */
    private Date bankSendTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_operation.GAS_ECHO
     *
     * @mbggenerated
     */
    private String gasEcho;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_operation.GAS_ECHO_TIME
     *
     * @mbggenerated
     */
    private Date gasEchoTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_operation.BANK_COMMAND
     *
     * @mbggenerated
     */
    private String bankCommand;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_operation.GAS_COMMAND
     *
     * @mbggenerated
     */
    private String gasCommand;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_operation.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_operation.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_operation.UPDATE_BY
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_operation.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_operation.DELFLAG
     *
     * @mbggenerated
     */
    private Short delflag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * mid_operation.DEL_DATE
     *
     * @mbggenerated
     */
    private Date delDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * mid_operation
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_operation.ID
     *
     * @return the value of mid_operation.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_operation.ID
     *
     * @param id the value for mid_operation.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_operation.BANK_IP
     *
     * @return the value of mid_operation.BANK_IP
     *
     * @mbggenerated
     */
    public String getBankIp() {
        return bankIp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_operation.BANK_IP
     *
     * @param bankIp the value for mid_operation.BANK_IP
     *
     * @mbggenerated
     */
    public void setBankIp(String bankIp) {
        this.bankIp = bankIp == null ? null : bankIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_operation.BANK_PORT
     *
     * @return the value of mid_operation.BANK_PORT
     *
     * @mbggenerated
     */
    public Integer getBankPort() {
        return bankPort;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_operation.BANK_PORT
     *
     * @param bankPort the value for mid_operation.BANK_PORT
     *
     * @mbggenerated
     */
    public void setBankPort(Integer bankPort) {
        this.bankPort = bankPort;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_operation.BANK_SEND
     *
     * @return the value of mid_operation.BANK_SEND
     *
     * @mbggenerated
     */
    public String getBankSend() {
        return bankSend;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_operation.BANK_SEND
     *
     * @param bankSend the value for mid_operation.BANK_SEND
     *
     * @mbggenerated
     */
    public void setBankSend(String bankSend) {
        this.bankSend = bankSend == null ? null : bankSend.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_operation.BANK_SEND_TIME
     *
     * @return the value of mid_operation.BANK_SEND_TIME
     *
     * @mbggenerated
     */
    public Date getBankSendTime() {
        return bankSendTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_operation.BANK_SEND_TIME
     *
     * @param bankSendTime the value for mid_operation.BANK_SEND_TIME
     *
     * @mbggenerated
     */
    public void setBankSendTime(Date bankSendTime) {
        this.bankSendTime = bankSendTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_operation.GAS_ECHO
     *
     * @return the value of mid_operation.GAS_ECHO
     *
     * @mbggenerated
     */
    public String getGasEcho() {
        return gasEcho;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_operation.GAS_ECHO
     *
     * @param gasEcho the value for mid_operation.GAS_ECHO
     *
     * @mbggenerated
     */
    public void setGasEcho(String gasEcho) {
        this.gasEcho = gasEcho == null ? null : gasEcho.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_operation.GAS_ECHO_TIME
     *
     * @return the value of mid_operation.GAS_ECHO_TIME
     *
     * @mbggenerated
     */
    public Date getGasEchoTime() {
        return gasEchoTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_operation.GAS_ECHO_TIME
     *
     * @param gasEchoTime the value for mid_operation.GAS_ECHO_TIME
     *
     * @mbggenerated
     */
    public void setGasEchoTime(Date gasEchoTime) {
        this.gasEchoTime = gasEchoTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_operation.BANK_COMMAND
     *
     * @return the value of mid_operation.BANK_COMMAND
     *
     * @mbggenerated
     */
    public String getBankCommand() {
        return bankCommand;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_operation.BANK_COMMAND
     *
     * @param bankCommand the value for mid_operation.BANK_COMMAND
     *
     * @mbggenerated
     */
    public void setBankCommand(String bankCommand) {
        this.bankCommand = bankCommand == null ? null : bankCommand.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_operation.GAS_COMMAND
     *
     * @return the value of mid_operation.GAS_COMMAND
     *
     * @mbggenerated
     */
    public String getGasCommand() {
        return gasCommand;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_operation.GAS_COMMAND
     *
     * @param gasCommand the value for mid_operation.GAS_COMMAND
     *
     * @mbggenerated
     */
    public void setGasCommand(String gasCommand) {
        this.gasCommand = gasCommand == null ? null : gasCommand.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_operation.STATE
     *
     * @return the value of mid_operation.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_operation.STATE
     *
     * @param state the value for mid_operation.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_operation.CREATE_DATE
     *
     * @return the value of mid_operation.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_operation.CREATE_DATE
     *
     * @param createDate the value for mid_operation.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_operation.UPDATE_BY
     *
     * @return the value of mid_operation.UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_operation.UPDATE_BY
     *
     * @param updateBy the value for mid_operation.UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_operation.UPDATE_DATE
     *
     * @return the value of mid_operation.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_operation.UPDATE_DATE
     *
     * @param updateDate the value for mid_operation.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_operation.DELFLAG
     *
     * @return the value of mid_operation.DELFLAG
     *
     * @mbggenerated
     */
    public Short getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_operation.DELFLAG
     *
     * @param delflag the value for mid_operation.DELFLAG
     *
     * @mbggenerated
     */
    public void setDelflag(Short delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column mid_operation.DEL_DATE
     *
     * @return the value of mid_operation.DEL_DATE
     *
     * @mbggenerated
     */
    public Date getDelDate() {
        return delDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * mid_operation.DEL_DATE
     *
     * @param delDate the value for mid_operation.DEL_DATE
     *
     * @mbggenerated
     */
    public void setDelDate(Date delDate) {
        this.delDate = delDate;
    }
}
